# Generated by Django 2.2 on 2019-04-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20190425_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
