# Generated by Django 2.2 on 2019-04-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20190426_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
