# Generated by Django 2.2 on 2019-04-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_variacion_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('subname', models.CharField(max_length=100)),
                ('peso', models.IntegerField(default=0)),
                ('hijos', models.ManyToManyField(blank=True, related_name='categoria_hijos', to='catalogo.Categoria')),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_padre', to='catalogo.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Categoria'),
        ),
    ]
