# Generated by Django 2.2 on 2019-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20190427_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='subname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
