# Generated by Django 2.2 on 2019-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20190427_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacion',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='variaciones',
            field=models.ManyToManyField(to='catalogo.Variacion'),
        ),
    ]
