# Generated by Django 2.2 on 2019-04-29 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20190429_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_padre', to='catalogo.Categoria'),
        ),
    ]
