# Generated by Django 2.2 on 2019-04-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20190429_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.IntegerField(default='random_num'),
        ),
    ]
